attestantio/vouch

- services/scheduler/basic/service.go
This removes a mutex lock followed by an unlock that has no code
inbetween.  This was a remnant from when job management was handled
within the control function, and is no longer required.
> Remove unused lock.

- CHANGELOG.md
- docs/metrics/prometheus.md
- services/metrics/null/service.go
- services/metrics/prometheus/client.go
- services/metrics/prometheus/service.go
- services/metrics/service.go
- strategies/aggregateattestation/best/aggregateattestation.go
- strategies/attestationdata/best/attestationdata.go
- strategies/beaconblockproposal/best/beaconblockproposal.go
This adds metrics to track the results of strategies across multiple nodes and operations.
> Strategy monitor

- services/signer/standard/signbeaconattestations.go
Accounts and distributed accounts were bundled up together for signing. This was non-optimal, as they have different requirements (single shot Vs. distributed threshold).  This separates them in to two groups, and signs them as separate sets of requests.
> Separate accounts before batch signing.

- CHANGELOG.md
- services/controller/standard/accountsrefresher.go
- services/controller/standard/attester.go
- services/controller/standard/proposer.go
- services/controller/standard/service.go
- services/controller/standard/synccommitteemessenger.go
- services/metrics/null/service.go
- services/metrics/prometheus/scheduler.go
- services/metrics/prometheus/service.go
- services/metrics/service.go
- services/scheduler/advanced/service.go
- services/scheduler/advanced/service_test.go
- services/scheduler/basic/service.go
- services/scheduler/basic/service_test.go
- services/scheduler/mock/service.go
- services/scheduler/service.go
Adds the concept of class to scheduler jobs.  Individual jobs are grouped by class for purposes of metrics, allowing for finer-grained detail about what is going on in the scheduler.
> Add scheduler job class.

- CHANGELOG.md
- services/attestationaggregator/standard/service.go
- services/attester/standard/service.go
- services/beaconblockproposer/standard/service.go
- services/metrics/null/service.go
- services/metrics/prometheus/attestation.go
- services/metrics/prometheus/attestationaggregation.go
- services/metrics/prometheus/beaconblockproposal.go
- services/metrics/prometheus/service.go
- services/metrics/prometheus/synccommitteeaggregation.go
- services/metrics/prometheus/synccommitteemessenger.go
- services/metrics/service.go
- services/synccommitteeaggregator/standard/service.go
- services/synccommitteemessenger/standard/service.go
Last slot metrics track the last slot acted upon by various Vouch operations.  This allows easy monitoring of the progress of Vouch in external systems.
> Add last slot metrics.

- clients.go
- main.go
- services/attestationaggregator/standard/service.go
- services/attester/standard/service.go
- services/beaconblockproposer/standard/propose.go
- services/beaconcommitteesubscriber/standard/subscribe.go
Catch situation where providers could return with no error but no result either.
> Catch nil return

- CHANGELOG.md
- Dockerfile
> Add ca certs

- CHANGELOG.md
- main.go
- services/submitter/multinode/submitaggregateattestations_test.go
- services/submitter/multinode/submitattestations_test.go
- services/submitter/multinode/submitbeaconblock_test.go
- services/submitter/multinode/submitbeaconcommitteesubscriptions_test.go
- services/submitter/multinode/submitproposalpreparations_test.go
- services/submitter/multinode/submitsynccommitteecontributions_test.go
- services/submitter/multinode/submitsynccommitteemessages_test.go
- services/submitter/multinode/submitsynccommitteesubscriptions_test.go
- testing/logger/capture.go
Update changelog and version number in preparation for release.
> Update release for 1.6.1.

- CHANGELOG.md
- main.go
- services/blockrelay/standard/auctionblock.go
- services/blockrelay/standard/metrics.go
Unchecked write to prometheus metrics moved to properly checked function.
> Fix crash in proposal with metrics disabled.

- .github/workflows/golangci-lint.yml
- .golangci.yml
- go.mod
- go.sum
- main.go
- services/controller/standard/parameters.go
- services/controller/standard/service.go
- services/graffitiprovider/dynamic/service.go
- testing/logger/capture.go
- util/id.go
Wait for genesis before doing anything else with beacon nodes, because some of them are uncooperative pre-genesis.
Also update go to 1.20
> Wait for genesis.

- CHANGELOG.md
- services/cache/standard/events.go
> Fix cache crash on nil head update.

- CHANGELOG.md
- main.go
- services/blockrelay/standard/auctionblock.go
Add resultant information about auction bids to trace.
> Auction result trace

- services/accountmanager/dirk/service.go
This is one potential fix for the duplicate key issue.
One thing that I am not entirely sure about is that I am opening multiple wallets concurrently with:
```
s.openWallet(ctx, walletName)
```
I have too little insights into the concurrency requirements around wallet management to understand if thats safe. Before this commit, everything was done serially. Please review.
> Eliminate duplicates from pubKeys

- CHANGELOG.md
- services/blockrelay/standard/auctionblock.go
- strategies/attestationdata/majority/attestationdata.go
- strategies/beaconblockproposal/best/beaconblockproposal.go
- strategies/builderbid/best/builderbid.go
Break down some large functions in strategies to increase maintainability.
> Tidy up strategies.

- .github/workflows/golangci-lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- services/attester/helpers.go
- services/attester/standard/attest.go
- services/attester/standard/attest_internal_test.go
- services/attester/standard/attest_test.go
- services/attester/standard/service.go
- services/attester/standard/service_test.go
Break out larger functions; more testing.
> Tidy up attestation function.

- services/attester/helpers.go
Fix incorrect sizing of array in recent update.
> Fix duties array.

- strategies/beaconblockroot/majority/beaconblockroot.go
A context was being cancelled then reused; separate out the contexts so that this does not happen.
> Separate beaconblockroot root context.

- CHANGELOG.md
- main.go
Update change log and version for 1.9.0-beta.1
> Updates to release beta

- services/scheduler/advanced/service_test.go
Flaky test reproduced by executing the below command in the vouch repository:
```shell
go test -count=1000 -run=TestMulti ./services/scheduler/advanced
```
> Update flaky test

- .golangci.yml
- CHANGELOG.md
- main.go
- services/accountmanager/dirk/service.go
- services/chaintime/standard/service.go
- util/epoch.go
- util/slot.go
Including tweaks so that linting passes.
> Relase 1.9.0.

- CHANGELOG.md
- services/blockrelay/standard/submitvalidatorregistrations.go
Backfill of https://github.com/attestantio/vouch/pull/263
> Ensure secondary registrations take place

- CHANGELOG.md
- services/controller/standard/events.go
Cherry pick from 1.9.x branch.
> Reduce log level of successful sync comittees.

- services/cache/standard/blockroottoslot.go
Address https://github.com/attestantio/vouch/pull/294 in electra branch
> Return fetched slot on cache miss

- CHANGELOG.md
- docs/configuration.md
- go.sum
- main.go
- mock/eth2client.go
- services/beaconblockproposer/service.go
- services/beaconblockproposer/standard/propose.go
- services/beaconblockproposer/standard/propose_test.go
- services/controller/standard/attester.go
- services/controller/standard/events_test.go
- services/controller/standard/parameters.go
- services/controller/standard/proposer.go
- services/controller/standard/service.go
- services/controller/standard/service_test.go
- services/multiinstance/always/metrics.go
- services/multiinstance/always/onattestationfailure.go
- services/multiinstance/always/onproposalfailure.go
- services/multiinstance/always/parameters.go
- services/multiinstance/always/service.go
- services/multiinstance/always/shouldattest.go
- services/multiinstance/always/shouldpropose.go
- services/multiinstance/service.go
- services/multiinstance/staticdelay/metrics.go
- services/multiinstance/staticdelay/onattestationfailure.go
- services/multiinstance/staticdelay/onproposalfailure.go
- services/multiinstance/staticdelay/parameters.go
- services/multiinstance/staticdelay/service.go
- services/multiinstance/staticdelay/service_test.go
- services/multiinstance/staticdelay/shouldattest.go
- services/multiinstance/staticdelay/shouldpropose.go
Create a framework for multi instance Vouch, along with an initial implementation that uses attestation data to confirm if other Vouch instances are active or not.
> Multi instance

- main.go
> Enable latest beaconblockroot strategy.

- services/controller/standard/synccommitteemessenger.go
As per https://github.com/attestantio/vouch/pull/328
This is a slight refactor of the above PR to address linter issues.
> Handle case where first sync committee period is epoch 0
