attestantio/vouch

- CHANGELOG.md
- docs/configuration.md
- main.go
- mock/eth2client.go
- services/accountmanager/mock/service.go
- services/attestationaggregator/mock/service.go
- services/attester/mock/service.go
- services/beaconblockproposer/mock/service.go
- services/beaconcommitteesubscriber/mock/service.go
- services/controller/standard/attester.go
- services/controller/standard/events.go
- services/controller/standard/parameters.go
- services/controller/standard/service.go
- services/controller/standard/service_test.go
- services/scheduler/mock/service.go
This adds a flag `controller.max-attestation-delay` that controls the maximum time that Vouch will wait until it starts to generates attestations for a slot.
> Max attestation delay

- services/accountmanager/dirk/service.go
#22 introduced an issue with updating accounts, where the code failed to wait for the waitgroup participants to finish.  This adds an explicit wait to ensure the waitgroup completes.
> Wait for waitgroup to complete.

- CHANGELOG.md
- docs/configuration.md
- go.mod
- main.go
- services/scheduler/advanced/parameters.go
- services/scheduler/advanced/service.go
- services/scheduler/advanced/service_test.go
- services/scheduler/service.go
The basic scheduler has shown weakness when handling high load, which manifests with the occasional deadlock situation.  This introduces an advanced scheduler, which contains additional features in an attempt to ensure that regardless of the concurrent load no job is ever left in an inconsistent state, explicitly with outstanding items to read on its channels.
> Add advanced scheduler.

- CHANGELOG.md
- main.go
- services/accountmanager/wallet/parameters.go
- services/accountmanager/wallet/service.go
This changes the wallet account manager to decrypt accounts in parallel, to reduce the time taken to update accounts on startup and refresh.
> Decrypt local accounts in parallel.

- clients.go
- docs/configuration.md
- logging.go
- main.go
- util/logging.go
- util/logging_test.go
The existing logging method was somewhat brittle.  This adds a utility function to obtain the most suitable logging level, walking up the configuration hiererachy until it finds a matching entry.
> Add hierarchical logging.

- CHANGELOG.md
- services/scheduler/advanced/service.go
- services/scheduler/advanced/service_test.go
It was possible for a job to be triggered just before it was due to run due to its timer.  This situation would cause a deadlock, resulting in Vouch terminating itself.  This adds explicit early removal from the jobs list as well as additional checks when trigger conditions are met.
> Avoid deadlock in advanced scheduler.

- CHANGELOG.md
- services/metrics/null/service.go
If there is no metrics configuration Vouch falls back to a null implementation.  This implementation was missing an interface, causing a cast exception.
This patch adds the required functions to implement the interface.
> Do not crash with no metrics configuration.

- CHANGELOG.md
- services/scheduler/advanced/service.go
The scheduler can hit a deadlock condition due to its use of synchronous channels.  This changes the scheduler channels to be asynchronous with a buffer size of 1, avoiding a deadlock situation.
> Add async channels to scheduler.

- util/scatter.go
- util/scatter_benchmark_test.go
- util/scatter_test.go
Scatter provides a helper for breaking a single range of processing in to multiple goroutines.
> Add scatter utility.

- CHANGELOG.md
- services/metrics/null/service.go
- services/metrics/prometheus/service.go
- services/metrics/prometheus/synccommitteeaggregation.go
- services/metrics/service.go
- services/synccommitteeaggregator/standard/service.go
This adds the coverage ratio for aggregate sync committee messages to metrics, providing the ability to see the outcome of the sync committee aggregation process.
> Add metrics for sync committee aggregation.

- CHANGELOG.md
- main.go
- services/metrics/prometheus/attestation.go
- services/metrics/prometheus/attestationaggregation.go
- services/metrics/prometheus/beaconblockproposal.go
- services/metrics/prometheus/beaconcommitteesubscription.go
- services/metrics/prometheus/parameters.go
- services/metrics/prometheus/service.go
- services/metrics/prometheus/service_test.go
- services/metrics/prometheus/synccommitteeaggregation.go
- services/metrics/prometheus/synccommitteemessenger.go
- services/metrics/prometheus/synccommitteesubscriber.go
- services/synccommitteemessenger/standard/service.go
Mark metrics state how far through a slot a particular operation takes place.  They are used to ensure that Vouch is performing in a timely fashion for all time-critical components of the validator client operation.
> Add mark metrics.

- docs/metrics/prometheus.md
- services/controller/standard/service.go
- services/metrics/prometheus/synccommitteeaggregation.go
- services/metrics/prometheus/synccommitteemessenger.go
Ensure that all metrics follow the same naming convention, and update documentation explaining the metrics' names and purposes.
> Tidy metrics.

- go.mod
- go.sum
- util/scatter_benchmark_test.go
- util/scatter_test.go
Scatter testing relied on Dirk.  It doesn't need to, so this removes the dependency.
> Tidy-up scatter testing.

- CHANGELOG.md
- services/controller/standard/service.go
Sync committee jobs were being created for period x at the beginning of period x-1.  Some beacon nodes were failing to update their internal information regarding the current sync committee period in time, resulting in them rejecting a request for sync committee duties.
This addresses the issue by only requesting data a few epochs before the new sync committee period comes in to effect.  This ensures that the node will be able to serve the requested data.
> Prepare sync committee jobs near change of period.

- clients.go
- go.mod
- go.sum
Vouch caches client definitions.  A multiclient definition with a single entry was indistinguishable from a standalone client, causing Vouch to confuse them.  This adds a 'multi:' namespace for the multiclient definition, ensuring that these remain separate.
> Separate multiclient definitions from individual.

- CHANGELOG.md
- services/synccommitteemessenger/standard/service.go
It is possible for a syncing beacon node to return nil for the beacon block root.  If this happens, log and return to avoid a crash.
> Avoid crash if beacon block root returns nil.

- CHANGELOG.md
- go.mod
- go.sum
- main.go
- mock/eth2client.go
- strategies/beaconblockproposal/best/beaconblockproposal.go
- strategies/beaconblockproposal/best/beaconblockproposal_test.go
- strategies/beaconblockproposal/best/events.go
- strategies/beaconblockproposal/best/events_internal_test.go
- strategies/beaconblockproposal/best/parameters.go
- strategies/beaconblockproposal/best/score.go
- strategies/beaconblockproposal/best/score_internal_test.go
- strategies/beaconblockproposal/best/service.go
- strategies/beaconblockproposal/best/service_test.go
The existing block proposal scoring system used only the contents of the block itself to decide a score.  However, this has limitations in the situation where some of the attestations included have an inclusion distance above 1.
This change alters the strategy to keep track the attestations in up to 32 slots' of historical blocks.  This data is then used in the block scoring process to give a zero score to attestations that are duplicates of previously-included attestations within the same chain as the block.
> Improved block proposal scoring

- CHANGELOG.md
- main.go
- mock/eth2client.go
- services/submitter/immediate/service_test.go
- services/submitter/multinode/parameters.go
- services/submitter/multinode/service.go
- services/submitter/multinode/service_test.go
- services/submitter/multinode/submitaggregateattestations.go
- services/submitter/multinode/submitaggregateattestations_test.go
- services/submitter/multinode/submitattestations.go
- services/submitter/multinode/submitattestations_test.go
- services/submitter/multinode/submitbeaconblock.go
- services/submitter/multinode/submitbeaconblock_test.go
- services/submitter/multinode/submitbeaconcommitteesubscriptions.go
- services/submitter/multinode/submitbeaconcommitteesubscriptions_test.go
- services/submitter/multinode/submitsynccommitteecontributions.go
- services/submitter/multinode/submitsynccommitteecontributions_test.go
- services/submitter/multinode/submitsynccommitteemessages.go
- services/submitter/multinode/submitsynccommitteemessages_test.go
- services/submitter/multinode/submitsynccommitteesubscriptions.go
- services/submitter/multinode/submitsynccommitteesubscriptions_test.go
The multinode submitter waited for all nodes to respond to it before returning, resulting in artifically high response times.  This now returns after the first successful result, which provides a more accurate metric for tracking the successful submission of the relevant data to the network.
> Return on first submission.

- main.go
- services/beaconcommitteesubscriber/standard/parameters.go
- services/beaconcommitteesubscriber/standard/service.go
- services/beaconcommitteesubscriber/standard/service_test.go
- services/beaconcommitteesubscriber/standard/subscribe.go
Beacon committee subscriptions were sending requests for all slots, including slots that occurred in the past during startup.  This cleans up the subscription request, only sending future slots at the time of sending.
> Clean up beacon committee subscriptions.

- strategies/beaconblockproposal/best/events.go
- strategies/beaconblockproposal/best/score.go
- strategies/beaconblockproposal/best/score_internal_test.go
Scoring target votes requires historical information for chain, however it is not feasible to fetch this at the time the block is proposed. This fetches blocks as they are added to the chain, and uses the information to score target votes accordingly.
> Add target scoring for block proposals.

- CHANGELOG.md
- main.go
- services/controller/standard/attester.go
- services/controller/standard/service.go
This changes Vouch's behaviour on a shutdown request, to wait for any outstanding attestation process for the current slot before starting the shutdown procedure.
Note that if there is an outstanding block proposal it should complete prior to the attestation starting, so is covered by the same process. If there is an outstanding sync committee duty we expect it to complete prior to the attestation, but even if not the impact of its loss will be relatively small compared to that of the attestations.
> Controlled shutdown.

- main.go
If an error occurs during startup prior to logging being successfully initialised then write to stder rather than log.
> Use stderr before logging.

- CHANGELOG.md
- docs/feerecipient.md
- services/feerecipientprovider/remote/feerecipients.go
If the remote endpoint is uncontactable it resulted in an error rather than falling back to cache or default.  This continues to log an error in this situation, however does falls back to cache or default as available.
> Handle missing remote endpoint.

- CHANGELOG.md
- docs/configuration.md
- main.go
- util/beaconnodeaddresses.go
- util/beaconnodeaddresses_test.go
- util/scatter_internal_test.go
This allows beacon node addresses to be configured hierarchically, with a single top-level value and overrides where required.  This simplifies the Vouch configuration, and also makes it more powerful.  A specific use case would be use of "silent nodes" to broadcast beacon block proposals from a different node or nodes from attestations.
> Add hierarchical beacon node addresses.

- docs/configuration.md
- docs/execlayer.md
Hey Jim, 
Saw you merging mev-boost stuff just as I was tinkering around with exactly that this evening. Addressed some issues with commas in the sample JSON in the docs and added syntax highlighting. Will report back on how I get on running mev-enabled vouch too if I run into any issues :)
> Fix some commas in json and add syntax highlighting

- go.mod
- go.sum
- main.go
- services/attester/standard/parameters.go
- services/attester/standard/service.go
- services/signer/standard/signbeaconattestations.go
This adds an in-memory map to the attester which it uses to check if it has already attested for each validator as part of its attesting routine.  This provides another layer of protection against possible double signing.
> Add attester checking.

- CHANGELOG.md
- strategies/aggregateattestation/best/aggregateattestation.go
- strategies/attestationdata/best/attestationdata.go
- strategies/beaconblockproposal/best/beaconblockproposal.go
- strategies/blindedbeaconblockproposal/best/blindedbeaconblockproposal.go
- strategies/synccommitteecontribution/best/synccommitteecontribution.go
Move to a dual-loop system, one pre-soft timeout and one post-soft timeout, to avoid repeating notifications of the soft timeout being reached.
> Handle soft timeout in separate loop.

- CHANGELOG.md
- go.mod
- go.sum
- services/beaconblockproposer/standard/propose.go
- services/blockrelay/standard/auctionblock.go
Vouch no longer complains if a relay returns no bid, but does so indicating success.
> Clean up logging for relays.

- CHANGELOG.md
- strategies/aggregateattestation/best/aggregateattestation.go
- strategies/beaconblockproposal/best/beaconblockproposal.go
- strategies/blindedbeaconblockproposal/best/blindedbeaconblockproposal.go
- strategies/synccommitteecontribution/best/synccommitteecontribution.go
Mark nil responses from beacon nodes as errors rather than dropping silently, allowing the strategy to return more quickly.
> Handle nil strategy responses.

- CHANGELOG.md
- strategies/aggregateattestation/best/aggregateattestation.go
- strategies/attestationdata/best/attestationdata.go
- strategies/beaconblockproposal/best/beaconblockproposal.go
- strategies/blindedbeaconblockproposal/best/blindedbeaconblockproposal.go
- strategies/synccommitteecontribution/best/synccommitteecontribution.go
Erros from strategies were somewhat opaque.  This patch includes the provider with error messages to understand better their source.
> Provide better errors from strategies.

- services/blockrelay/standard/auctionblock.go
- services/blockrelay/standard/executionconfig.go
A zero-value bid could be selected if it was the first bid returned from relays.  This change ensures that zero value bids are never selected as candidates for block selection.
> Ignore zero-value bids.

- main.go
- services/blockrelay/v1/executionconfig.go
- services/blockrelay/v1/executionconfig_test.go
It was possible for a registration's gas limit to be 0 if not present if the default configuration of a V1 proposer configuration did not provide a gas limit and it was called upon to be used in lieu of a specific proposer configuration.  Ensure that the fallback gas limit is used in this situation.
> Ensure that registration gas limit is not 0.

- CHANGELOG.md
- main.go
Accountmanager was starting Dirk on an incorrect basis, and multiple accountmangers could be defined and fail to start silently.  Address both of these issues.
> Tidy up accountmanager startup.

- CHANGELOG.md
- docs/executionconfig.md
- services/blockrelay/v2/executionconfig.go
- services/blockrelay/v2/executionconfig_test.go
In some situations the proposer relay configuration did not inherit all higher-level values.  This patch ensures that all values are inherited correctly.
> Manage execution configuration inheritence.

- CHANGELOG.md
- services/beaconblockproposer/standard/propose.go
- services/beaconblockproposer/standard/propose_internal_test.go
- services/beaconblockproposer/standard/propose_test.go
- services/beaconblockproposer/standard/service_test.go
Fetch both blinded (if required) and unblinded (always) beacon block proposals in parallel, increasing the speed of generating local blocks when relays are unavailable or generating low-value blocks.
> Use parallel production for block proposals.

- CHANGELOG.md
- services/accountmanager/dirk/service.go
Reduce the amount of computation by creating the public key array at the time accounts are obtained.
> Create public key array once not on each use.

- CHANGELOG.md
- services/controller/standard/service.go
Attestations were not scheduled if there are no active validators, but in the case where this is Vouch's first validator ever we need to attempt to schedule regardless to avoid missing the first attestation.
> Ensure first attestations are scheduled.

- README.md
We have enabled debug api by default in our latest release (v1.20.0)
> Remove note about Lodestar required parameters

- strategies/builderbid/best/builderbid.go
The best value block was not selected.
`bestScore` is a pointer to a `big.Int`, and when you do `bestScore = resp.score`, you're changing the pointer itself, not the data it points to. This change will not be visible outside the function.
> fix: bestScore is a pointer to a big.Int and we were changing the pointer itself instead of changing the data on the pointer

- CHANGELOG.md
- services/cache/standard/blockroottoslot.go
- services/cache/standard/metrics.go
Allow tracking of failures to resolve root to slot lookups.
> Add 'failed' dimension for root to slot lookup metrics.

- CHANGELOG.md
- docs/configuration.md
- main.go
- services/accountmanager/dirk/service.go
- services/accountmanager/mock/service.go
- services/accountmanager/service.go
- services/accountmanager/utils/utils.go
- services/accountmanager/wallet/service.go
- services/controller/standard/events.go
- services/controller/standard/service.go
- services/controller/standard/synccommitteemessenger.go
- alter logic for determining sync committee eligible accounts
- enable first strategies to be defined for beaconblockheader and signedbeaconblock
> Use strategy for providers and alter sync committee eligibile logic

- docs/configuration.md
- main.go
- services/blockrelay/builderconfig.go
- strategies/builderbid/best/builderbid.go
- strategies/builderbid/deadline/builderbid.go
Boost is a percentage multiplier and should accommodate for the same requirements as factor but also gives the validator more precise control on how much they are willing to increase privileged relays score.
One additional feature of this is that validators could also create a new group and reduce the score of a specific relay. At the moment we don't see this as an issue, but would love to get your opinion on this.
> feat: changing builder configs factor to be a percentage

- main.go
Ensure that milliseconds are displayed in the default log timestamp format, even if they are 0.
> Force milliseconds in default log timestamp format.

- Dockerfile
Fixes warning when running `docker --debug build -t attestant/vouch .` with `Docker version 27.2.0, build 3ab4256`
Output:
```
1 warning found:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
The 'as' keyword should match the case of the 'from' keyword
More info: https://docs.docker.com/go/dockerfile/rule/from-as-casing/
Dockerfile:1
--------------------
1 | >>> FROM golang:1.22-bookworm as builder
2 |
3 |     WORKDIR /app
--------------------
```
> fix 'FromAsCasing' warning on docker image build

- strategies/signedbeaconblock/first/signedbeaconblock.go
Attempt to reduce the signed beacon block metrics by not incrementing in expected error situations.
> Reduce the failed signed beacon block metrics

- CHANGELOG.md
- main.go
- services/blockrelay/standard/submitvalidatorregistrations.go
In some situations the secondary registrations were not fully captured, resulting in some validators not letting their beacon nodes know they wanted to use MEV relays.  This addresses that issue.
> Ensure secondary registrations take place..

- CHANGELOG.md
- services/metrics/prometheus/client.go
- services/metrics/prometheus/client_test.go
Standardise the provider format for strategy and client operation metrics.
> Standardise provider format

- services/blockrelay/v2/executionconfig.go
- services/blockrelay/v2/executionconfig_test.go
Fix default gas limit on execution config
Example not working gas limit on execution config - instead of 40000000, relay would use default 3000000.
```
{
"version": 2,
"fee_recipient": "...redacted...",
"relays": {
"https://holesky.titanrelay.xyz": {
"public_key": "0xaa58208899c6105603b74396734a6263cc7d947f444f396a90f7b7d3e65d102aec7e5e5291b27e08d02c50a050825c2f"
}
},
"proposers": [],
"gas_limit": "40000000"
}
```
> Fix default gas limit on execution config

- README.md
- docs/metrics/grafana.md
- The dashboard is published on Grafana here: https://grafana.com/grafana/dashboards/22199-vouch-attestant/
- The dashboard is showing up in the public search: https://grafana.com/grafana/dashboards/?search=vouch
- Sadly, it doesn't look like there is an auto-update when the public dashboard is updated. It looks like the way to get the updates is to import the dashboard again and overwrite it. 
- Updated docs to describe importing from Grafana directly
- Removed the json file present in the repo
> Add details for importing Vouch dashboard from Grafana

- services/blockrelay/standard/executionconfig.go
When vouch was configured to fetch the blockrelay/executionconfig from an http endpoint, the respective majordomo call did not properly set the `Content-Type` and `Accept` headers. Instead, `Content-Type: text/plain` was sent.
This commit adds the respective `MIMEType` value to the majordomo context [1] so that these requests are now sent with the `Content-Type` and `Accept` headers set to `application/json`.
I ran the tests locally and they were passing.  I also ran an integration test with an `mitmproxy` for introspection of the request:
Incorrect header is sent and our endpoint rejects the unsupported media type text/plain
```yml
[::1]:53462: POST http://localhost:8082/execution-configuration
Host: localhost:8082
User-Agent: Go-http-client/1.1
Content-Length: 405
Accept-Encoding: gzip …
```
> Use correct mime type on fetch of execution config

- .golangci.yml
- main.go
The logs stating we are altair/bellatrix/capella capable are a bit misleading as we don't have corresponding deneb/electra log messages. 
Removing the logs saying past forks are supported. 
Some linter updates also
> Remove info logs from past forks

- services/blockrelay/standard/submitvalidatorregistrations.go
Avoids 'context deadline exceeded' messages which are ultimately harmless but cause user concern and noise in the logs.
> Update validator registration timeout.
